### ISSUE TITLE
Thread Handling 

### ISSUE THREAD

**Issue by rooparsh** [ACM-VIT/gitpositive#12]
The app is not following proper thread handling as well as the API call is being made again and again on orientation change.

**Comment by rooparsh** [comment]
@rishuyadav This issue is fixed in [PR](https://github.com/ACM-VIT/gitpositive/pull/13). Please check and merge it.

**Comment by DarthBenro008** [comment]
Closed via c31c953a5649fab1dd13af6e33b7480f9e0ca480
