### ISSUE TITLE
Login Screen broken on orientation change

### ISSUE THREAD

**Issue by rishuyadav** [ACM-VIT/gitpositive#17]
The Home screen views misbehave on changing the orientation of the app to landscape, have to fix the Layout Constraints, and probably roll it inside a Nested Scrollview.

Issue Image below:
![image](https://user-images.githubusercontent.com/72988817/135718152-f7a3fc3f-c7d8-4a87-b06c-becc49a33dfa.png)

**Comment by usmanghanidev** [comment]
Fixing this issue.
