### ISSUE TITLE
An error screen upon no internet connectivity.

### ISSUE THREAD

**Issue by gaganmalvi** [ACM-VIT/gitpositive#23]
- Right now, the app shows default values in the card if there is no internet connection.
- Need to show "no internet connection" upon encountering such a case.
- For example the screen can be -
![Google Pixel 2 - 6](https://user-images.githubusercontent.com/26477157/135724192-958a17f8-46dd-48b7-a1d4-d57204c8b89e.png)

**Comment by prasoonsoni** [comment]
Can you assign me this issue I can try this?

**Comment by rishuyadav** [comment]
Yep assigned, go ahead with it @prasoonsoni 👍
