### ISSUE TITLE
UI enhancement of Repositories screen [Jetpack Compose]

### ISSUE THREAD

**Issue by gaganmalvi** [ACM-VIT/gitpositive#26]
- Need to follow current app theming
As a theoretical example - 
![image](https://user-images.githubusercontent.com/26477157/135726979-ae344c8a-d20a-481e-b94a-5c917c0908a1.png)
Current screen - 
![image](https://user-images.githubusercontent.com/26477157/135727017-9321112c-6a70-4f34-9cf0-148bbbd4ace2.png)

**Comment by rudrankbasant** [comment]
Please assign me this issue.

**Comment by gaganmalvi** [comment]
Personal DM from @rudrankbasant, said he couldn't continue, abandoning his PR. 
@V9vek's PR merged, closing his issue. 
Happy Hacktoberfest!

**Comment by gaganmalvi** [comment]
There's still scope for improvement, so I'll keep this issue alive.
