### ISSUE TITLE
Bottom Navigation Bar colour not dynamic

### ISSUE THREAD

**Issue by Chirayu123dot** [ACM-VIT/gitpositive#28]
The colour of the bottom navigation bar is white in both dark & light themes of the app

**Current state**
![finla](https://user-images.githubusercontent.com/72456458/135746175-0705efb1-2174-4700-8164-7b3e4b53946f.png)

**Expected state**
![finla2](https://user-images.githubusercontent.com/72456458/135746292-60b4a344-f647-4f42-b0b0-1969b4a5480f.png)

I would like to be assigned this issue.

**Comment by rishuyadav** [comment]
Go ahead with it @Chirayu123dot 🚀
