### ISSUE TITLE
Infinite Loading Dialog bug

### ISSUE THREAD

**Issue by rishuyadav** [ACM-VIT/gitpositive#29]
If the username entered doesn't exist, the Loading dialog keeps on displaying and can't be canceled.

![image](https://user-images.githubusercontent.com/72988817/135748120-0e7a152e-dc66-4c0d-a088-469925293153.png)

**Comment by rooparsh** [comment]
@rishuyadav This issue is fixed in [PR](https://github.com/ACM-VIT/gitpositive/pull/31)

**Comment by prasoonsoni** [comment]
If this still persists, can you assign me this issue?

**Comment by rishuyadav** [comment]
> If this still persists, can you assign me this issue?

Hey @prasoonsoni This issue has been solved by @rooparsh glad to hear u are interested pls check other open issues on the repo
