### ISSUE TITLE
View Repositories doesn't work

### ISSUE THREAD

**Issue by gaganmalvi** [ACM-VIT/gitpositive#3]
- New fragment showing all repositories via api.github.com in a CardView inside a RecyclerView

**Comment by Kardelio** [comment]
Hey @gaganmalvi can I just check, is this issue to create a new screen (that doesn't exist yet) that will list all the repositories that are returned from the `api.github.com` response?
Is that correct?
If so would you mind if I take a crack at this ticket, if no-one else is already working on it?

**Comment by gaganmalvi** [comment]
Yep, exactly. 
I have an idea in mind as well if you want.
![Google Pixel 2 - 4](https://user-images.githubusercontent.com/26477157/135723453-e8f6b292-6dc5-48f9-97f5-3ef4f6fba6c9.png)
You can have a go at it :))

**Comment by gaganmalvi** [comment]
Also @Kardelio, this issue could be paired up with issue number #4 as well, since we don't receive all the names of the repositories via the public API, if I can recall correctly.

**Comment by Kardelio** [comment]
Ok awesome! Looks good!
Would you mind assigning me to this issue and Ill get started :)

Also extra question would you mind if I use Jetpack Compose for the UI on this new screen?

**Comment by gaganmalvi** [comment]
Sure, you can use Jetpack Compose. :)

**Comment by gaganmalvi** [comment]
Do you want to pursue the OAuth in a separate PR as well?

**Comment by Kardelio** [comment]
> Sure, you can use Jetpack Compose. :)

Thank you <3

> Do you want to pursue the OAuth in a separate PR as well?

For now ill leave that for the moment but maybe after I have dealt with this new screen ill come back and tackle this :)

**Comment by gaganmalvi** [comment]
Also, a small idea - you could add an intent as well where on tap, the concerned repository opens in a web browser.

**Comment by Kardelio** [comment]
Addressed in #25 @gaganmalvi 

Also whilst i was devving the main branch changed and it looks like the UI color scheme changed considerably so i changed my code to match the new theming

**Comment by gaganmalvi** [comment]
```
e: /home/runner/work/gitpositive/gitpositive/app/src/main/java/org/acmvit/gitpositive/MainActivity.kt: (63, 17): Unresolved reference: viewRepositories

> Task :app:compileDebugKotlin FAILED
w: ATTENTION!
This build uses unsafe internal compiler arguments:

-XXLanguage:+NonParenthesizedAnnotationsOnFunctionalTypes

This mode is not recommended for production use,
as no stability/compatibility guarantees are given on
compiler or generated code. Use it at your own risk!


FAILURE: Build failed with an exception.
```
Merge screwed, and yeah the theme changed in the previous commit :( 
Just the GitPositive text on the top though.

**Comment by gaganmalvi** [comment]
https://github.com/ACM-VIT/gitpositive/pull/25/commits/2b3534810f282348606ae47a061ba970c9c75a16#diff-890c768d5041bf31eb05673f33ad9d0ff7a42a754da46062eec65969d735c7ddR161
This could be viewRepositories, no?

**Comment by Kardelio** [comment]
Ahhh hold on this was a mergeissue, ill fix it right now :) @gaganmalvi

**Comment by Kardelio** [comment]
Ok @gaganmalvi sorted! 
This was due to the merge as the `main` branch had changed after I had done my work so i could not push.
So i merged in main and must have left this reference in

**Comment by gaganmalvi** [comment]
Sure sure, thanks for the contribution! Will test once, and post-testing will merge asap.

**Comment by Kardelio** [comment]
@gaganmalvi Legend! Thank you so much!
i setup the basic UI of the repo list, there is probably much more that can be done to improve the UI on this screen, but I thought maybe someone else that wants to try out some compose could do that in another issue maybe ? 👍 
Anyway thanks for letting me get involved and awesome project btw! <3

**Comment by gaganmalvi** [comment]
The basic UI seems nice, and yes, maybe someone could pick it up from there 😉
Happy Hacktoberfest!

**Comment by gaganmalvi** [comment]
Also, if you could, you could add an intent to open the repository in a web browser as well?

**Comment by Kardelio** [comment]
@gaganmalvi yep sure, ill do that now 💯

**Comment by gaganmalvi** [comment]
Alright, thanks a ton! 😄

**Comment by Kardelio** [comment]
@gaganmalvi done 👍  check it out <3

**Comment by gaganmalvi** [comment]
on it!

**Comment by gaganmalvi** [comment]
lgtm, merging :))
