### ISSUE TITLE
Bottom Sheet fragment showing followers and following

### ISSUE THREAD

**Issue by rishuyadav** [ACM-VIT/gitpositive#38]
On Clicking the followers/ following button, the user should see a bottom sheet fragment which can be scrolled and can be extended to full screen also, the fragment contains the name of followers/ following with their avatar.

**Comment by 1407arjun** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by prasoonsoni** [comment]
I'm interested in solving this issue.
