### ISSUE TITLE
App icon is not proper.

### ISSUE THREAD

**Issue by prasoonsoni** [ACM-VIT/gitpositive#42]
![Screenshot_20211005-004907_One UI Home](https://user-images.githubusercontent.com/75159757/135911426-69dac2d9-9d6b-4772-9689-e899bc49f90f.jpg)

In this App Icon, there are white lines in the corner, I think that is not looking good.

**Comment by prasoonsoni** [comment]
If it is to be solved please assign me the issue.

**Comment by Avinaash7** [comment]
All the best @prasoonsoni !!
