### ISSUE TITLE
Suggest only a maximum of three suggestions for any sequence in the dropdown suggestion list.

### ISSUE THREAD

**Issue by Avinaash7** [ACM-VIT/gitpositive#51]
https://user-images.githubusercontent.com/71816352/136045645-39c5cd47-19b3-4cdb-9fd6-2badadbed2e8.mp4

Displaying all the usernames spoils the UI of the app, make sure to suggest only a maximum of 3 usernames.

Note :- 
1. The Database can store many usernames, but if more than 3 usernames typed have the same first two letters then store only the recent 3 usernames of that sequence.

**Comment by rooparsh** [comment]
@Avinaash7 assign this to me. Will look into it.

**Comment by Avinaash7** [comment]
> @Avinaash7 assign this to me. Will look into it.

Sure! Good Luck

**Comment by rooparsh** [comment]
@Avinaash7 issue addressed in PR [Link](https://github.com/ACM-VIT/gitpositive/pull/56). Review and merge it.

**Comment by Avinaash7** [comment]
> @Avinaash7 issue addressed in PR [Link](https://github.com/ACM-VIT/gitpositive/pull/56). Review and merge it.

App keeps crashing
Check and correct your code, Good luck!!
