### ISSUE TITLE
Fix null values in repo listing

### ISSUE THREAD

**Issue by ersascape** [ACM-VIT/gitpositive#67]
Steps to reproduce: 
- On pressing XYZ repositories card, it opens up a list with repositories
- Here, if language is empty, it returns null

Suggested fix: Hide the entire language part if value for language is returned null

**Comment by prasoonsoni** [comment]
Can you please assign me this issue?

**Comment by rishuyadav** [comment]
Issue resolved in pr #71 , closing it
