### ISSUE TITLE
Status Bar not distinctly visible

### ISSUE THREAD

**Issue by rishuyadav** [ACM-VIT/gitpositive#9]
Status Bar color is set as that of bg_color(#ffffff) white which is same as the default status bar icon colors, so icons are not visible.
Check below image for reference.

![image](https://user-images.githubusercontent.com/72988817/135707884-6172e3c3-39eb-44dc-9dee-6bec5ec2a3c8.png)

**Comment by UbadahJ** [comment]
@rishuyadav Assign me
